INSERT INTO SITE_USER (ID, USERNAME, PASSWORD, ENABLED, LAST_PASSWORD_RESET_DATE) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO SITE_USER (ID, USERNAME, PASSWORD, ENABLED, LAST_PASSWORD_RESET_DATE) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 1, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));
INSERT INTO SITE_USER (ID, USERNAME, PASSWORD, ENABLED, LAST_PASSWORD_RESET_DATE) VALUES (3, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 0, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO SITE_USER_AUTHORITIES (SITE_USER_ID, AUTHORITIES_ID) VALUES (1, 1);
INSERT INTO SITE_USER_AUTHORITIES (SITE_USER_ID, AUTHORITIES_ID) VALUES (1, 2);
INSERT INTO SITE_USER_AUTHORITIES (SITE_USER_ID, AUTHORITIES_ID) VALUES (2, 1);
INSERT INTO SITE_USER_AUTHORITIES (SITE_USER_ID, AUTHORITIES_ID) VALUES (3, 1);
